services:
  redis:
    image: docker.io/bitnami/redis:7.4
    container_name: redis
    # env_file:
    #   - ./.env/.env.dev.msg-broker.reddis
    environment:
      #   # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
